# Generated by Django 6.0.3 on 2026-04-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company_percentage', models.IntegerField()),
                ('individual_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.level')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_period', models.CharField(max_length=100)),
                ('employee_comment', models.TextField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.employee')),
            ],
            options={
                'unique_together': {('employee', 'performance_period')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('measure', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('employee_actual', models.FloatField(blank=True, null=True)),
                ('manager_actual', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='api.evaluation')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('evaluation', 'order')},
            },
        ),
    ]
